### PR TITLE
Force rewind in __toString() method

### PR DESCRIPTION
**Pull request by roukmoute**
We respect the PSR that MUST attempt to seek to the beginning of the stream before reading data.

### CODE REVIEW

**Review by brentscheffler — COMMENTED** [review]
Not all resources can be rewound. And if you take a look at the `rewind()` method, it will throw an exception if the underlying resource is not seekable (or the resource has been detached.)

Maybe try a `if ( $this->isSeekable() ) { $this->rewind(); }`

**Comment by roukmoute** [comment]
You're right the PSR indicates: `This method MUST NOT raise an exception`

**Review by brentscheffler — APPROVED** [review]

**Comment by brentscheffler** [comment]
Looks good - thank you!

**Comment by roukmoute** [comment]
Could you create a new release please?

**Pull request merged**
